version: '3.8'

services:
  islamic-study-site:
    build: .
    ports:
      - "80:80"
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/var/log/supervisor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
