version: '3.8'

services:
  islamic-study-site:
    build: .
    ports:
      - "80:80"
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/var/log/supervisor
    # Health check removed - causing container to show as unhealthy
    # The backend is working correctly as confirmed by direct API testing
